import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { NavBar } from "./components/NavBar";
import { Outfit } from "next/font/google";
import SideNav from "./components/SideNav";
import VideoDataProvider from "./videoDataContext";
import { SessionProvider } from "next-auth/react";

const outfit = Outfit({
  // weight: "100 900",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AI Shorts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={outfit.className}>
        <SessionProvider>
          <VideoDataProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <NavBar />
              <div className="flex">
                <SideNav />
                {children}
              </div>
            </ThemeProvider>
          </VideoDataProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
